### ISSUE TITLE
Remove old demos

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/at_demos#108]
### Is your feature request related to a problem? Please describe.

N/A

### Describe the solution you'd like

Remove at_cookbook, at_hello_world

@gkc should we remove at_demo_data?

**Comment by JeremyTubongbanua** [comment]
I would say no, since we don't have plan to have any other folders in the repo (like tests, tools, etc,.)

But we do that in [at_widgets](https://github.com/atsign-foundation/at_widgets)
