### ISSUE TITLE
Missing documentation - at_demo_data (Scores Tab)

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_demos#19]
[Scores tab](https://pub.dev/packages/at_demo_data/score) in pub.dev missing documentation for:

- [x] follow dart file conventions
- [x] provide documentation
- [x] pass static analysis
- [x] support sound null safety

**Comment by murali-shris** [comment]
null safety changes published https://pub.dev/packages/at_demo_data/versions/1.0.0

**Comment by ksanty** [comment]
> null safety changes published https://pub.dev/packages/at_demo_data/versions/1.0.0

Thanks @murali-shris can you add sprint points, so we can track?  TY
