### ISSUE TITLE
Get Started with C Demos

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/at_demos#221]
Write demos to help aid the doc site with examples.

- [x] 1-authentication
- [x] 2a-create-public-atkey
- [x] 2b-create-self-atkey
- [x] 2c-create-shared-atkey
- [x] 2d-create-atkey-with-metadata
- [x] 3a-put-public-key
- [x] 3b-put-self-atkey
- [x] 3c-put-shared-atkey
- [x] 3d-get-public-atkey
- [x] 3e-get-self-atkey
- [x] 3f-get-shared-atkey
- [x] 4a-monitor
- [x] 4b-notify
- [x] 5a-hooks

**Comment by JeremyTubongbanua** [comment]
@XavierChanth I would like to propose this structure for the demos

```
 1-authentication
 2a-atkey
 2b-atkey-with-metadata
 3a-put-self-key
 3b-get-self-key
 4a-put-shared-key
 4b-get-shared-key
 5a-put-public-key
 5b-get-public-key
 6a-notify
 6b-monitor
 7a-hooks
```

Is that cool?

**Comment by xavierchanth** [comment]
Yeah, you could also do something like this:

The docs aren't numbered but they are in this order
```
- Get started (mainly would be the CMakeList.txt file)
- Authentication
- atKey Reference
- CRUD ops
- Notifications
- Extras (such as hooks)
```

e.g. Then you could say on the CRUD page, the CRUD examples are all number 3.
```
 1a-authentication
 2a-atkey
 2b-atkey-with-metadata
 3a-put-self-key
 3b-get-self-key
 3c-put-shared-key
 3d-get-shared-key
 3e-put-public-key
 3f-get-public-key
 4a-notify
 4b-monitor
 5a-hooks
```

But whatever you prefer, fine by me.

**Comment by JeremyTubongbanua** [comment]
Found a bug with fetch content, allocating 1 SP to fix documentation on gitbooks and examples
