### ISSUE TITLE
Issues in the at_chats demo app

### ISSUE THREAD

**Issue by purnimavenkatasubbu** [atsign-foundation/at_demos#28]
**Describe the bug**
Messages were being delivered as expected for a while. But after some time the messages were not being delivered to the receiver atsign. Once I restart the app, All the previous messages were delivered again

**To Reproduce**
1. First I installed the at_chat demo app in as atsign A and atsign B in 2 devices
2. Then send message from atsign A to atsign B
3. And then checked the chat history in the atsign B

**Expected behavior**
All the chats should be displayed

**Screenshots**

https://user-images.githubusercontent.com/43639593/130640813-3ad305c8-4fa2-4977-90d8-d38eb9fa29c4.mp4

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone11]
 - OS: [e.g. iOS14.1]
 - Version [e.g. 59]

**Were you using an @‎application when the bug was found?**
  - [e.g. @‎ chat]

**Additional context**
Attaching the app logs
[chatDemoApp_logs.docx](https://github.com/atsign-foundation/at_demos/files/7040219/chatDemoApp_logs.docx)

**Comment by yahu1031** [comment]
@purnimavenkatasubbu Have you tried with android?

**Comment by purnimavenkatasubbu** [comment]
Yes on Android device.

**Comment by purnimavenkatasubbu** [comment]
Retested the scenario. It looks fine.
![Screenshot from 2021-08-27 12-15-08](https://user-images.githubusercontent.com/43639593/131084328-b6a69c78-538c-40e8-ad14-f8fb1fbe3081.png)
![1630046764439](https://user-images.githubusercontent.com/43639593/131084343-795e2446-5eb9-4d70-ad70-1e71ec2c45dd.JPEG)
