### ISSUE TITLE
ReadMe.md -- Add current build/workflow status and license badge

### ISSUE THREAD

**Issue by TylerTrott** [atsign-foundation/at_demos#32]
A status badge shows whether a workflow is currently failing or passing. In addition	to this, it is important to show our Github BSD 3-clause License badge on all public repositories.

A common place to add the status and license badge is in the ```README.md``` at the top alongside the GitHub License.

```diff
+ ![example workflow](https://github.com/<OWNER>/<REPOSITORY>/actions/workflows/<WORKFLOW_FILE>/badge.svg)
+ [![GitHub License](https://img.shields.io/badge/license-BSD3-blue.svg)](./LICENSE)
```

**Comment by gcshisir** [comment]
If this issue is not assigned to anyone I would like to work on it.

**Comment by TylerTrott** [comment]
This was pushed and merged
