### ISSUE TITLE
Unlist at_demo_data on Pub.dev

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_demos#35]
Unlist the following packages on Pub.dev ~ @nickelskevin to provide further details

- [x] at_demo_data

**Comment by ksanty** [comment]
Also ensure we leave the readme.md on Github and look for updates (like logo and readme.md standard archetype)

- [ ] Review for current logo
- [ ] Does it map to current standard archetype

**Comment by xavierchanth** [comment]
Unlisted it @ksanty @nickelskevin, closing this issue.
