### ISSUE TITLE
Update at_demo_data

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_demos#37]
Update Github documentation for to be [unlisted pub.dev package at_demo_data](https://github.com/atsign-foundation/at_demos/issues/35).  

Review [at_demo_data ](https://github.com/atsign-foundation/at_demos/tree/trunk/at_demo_data) readme.md, changelog.md and look for standard archetype template updates to make current.  Repo will remain active even though it will be unlisted on Pub.dev.

- [x]  Review for current logo
- [x] Add badging
- [x]  Does text body map to current standard archetype for consistency (dependency on [archetype update](https://github.com/atsign-foundation/at_client_sdk/issues/398))
- [x] Update readme.md
- [x] Update changelog.md

**Comment by XavierChanth** [comment]
@cpswan @nickelskevin @gkc Should I bother updating this if it is currently unlisted? I don't think this package is being used anymore.
